project:
  type: website

website:
  title: "AI/ML for Industry [Training Program@IIT Delhi]"
  navbar:
    right:
      - text: "Home"
        href: index.qmd
      - text: "Course Types"
        menu:
          - text: "6-month Certificate Course"
            href: 'aiml-6-months-iitd-certificate.qmd'  
          - text: "Sponsored Programme"
            href: sponsored.qmd
          - text: "3-Day Bootcamp"
            href: bootcamp.qmd
      - text: "Course Editions"
        menu:
          - text: "6-Month Certificate Course [2024, Batch 03]"
            href: certificate-batch03.qmd
          - text: "5-Day Program for CAG/IAAS Officers [2024]"
            href: cag.qmd
          - text: "6-Month Certificate Course [2024, Batch 02]"
            href: certificate-batch02.qmd
          - text: "1-Day Program for Young Presidents' Organization [2024]"
            href: ypo.qmd
          - text: "3-Day AI/ML Bootcamp [2023]"
            href: bootcamp-2023.qmd
          - text: "6-Month Certificate Course [2023, Batch 01]"
            href: certificate-batch01.qmd
      - text: "Team"
        href: team.qmd
      - text: "Contact"
        href: contact.qmd
    search: false

format:
  html:
    favicon: favicon.png
    theme: United
